# Tutorial

In [1]:
# Loading all helper functions
import sys
sys.path.insert(0, '..')
from src.models.data_utils import *
from src.models.model_utils import *
from src.models.train_model import *
from tqdm import tqdm

## General info:

### Code structure
- Helper functions are stored in src/models
- Data is stored in data/processed

### Corpora and annotation
#### Dicta-Sign
Annotations include (see more detail in the ortolang repo):
* **fls**: fully-lexical signs, encoded as categorical values (gloss indices)
* **PT**:    pointing signs, encoded as binary
* **PT_PRO1**, **PT_PRO2**, **PT_PRO3**, **PT_LOC**, **PT_DET**, **PT_LBUOY**, **PT_BUOY**: sub-categories for pointing signs, encoded as binary
* **DS**:    depicting signs, encoded as binary
* **DSA**, **DSG**, **DSL**, **DSM**, **DSS**, **DST**, **DSX**: sub-categories for depicting signs, encoded as binary
* **FBUOY**: fragment buoys, encoded as binary
* **N**:     numbering signs, encoded as binary
* **FS**:    fingerspelling signs, encoded as binary

#### NCSLGR
Annotations include (all data is binary):
* **lexical_with_ns_not_fs**: lexical signs, including numbering signs but excluding fingerspelling signs
* **fingerspelling**, **fingerspelled_loan_signs**: fingerspelling signs, finglerspelling loan signs
* **IX_1p**, **IX_2p**, **IX_3p**, **IX_loc**: sub-categories for pointing signs
* **POSS**, **SELF**: possessive pronouns
* **DCL**, **LCL**, **SCL**, **BCL**, **ICL**, **BPCL**, **PCL**: sub-categories for classifier signs (i.e. depicting signs)
* **gesture**: culturally shared gestures
* **part_indef**
* **other**

### Type of input features
Originally, this code was designed around preprocessed features for each frame. Possible features types are : 
- **2Draw**
- **2Draw_HS**
- **2Draw_HS_noOP**
- **2Draw_noHands**
- **2Dfeatures**
- **2Dfeatures_HS**
- **2Dfeatures_HS_noOP**
- **2Dfeatures_noHands**
- **3Draw**
- **3Draw_HS**
- **3Draw_HS_noOP**
- **3Draw_noHands**
- **3Dfeatures**
- **3Dfeatures_HS**
- **3Dfeatures_HS_noOP**
- **3Dfeatures_noHands**

which correspond to 2D or 3D data, raw OpenPose or preprocessed body and face data, including or excluding hand shape estimates, including or excluding OpenPose hand data.

The main data function `get_data_concatenated` requires a features dictionary, which can be obtained with the `getFeaturesDict` function.

Recently, we also added direct image input to the model, but it has not been tested thoroughly.

### Model outputs
The model can be trained for the recognition of:
- one or several (N) mixed linguistic descriptors in parallel, possibly simultaneously true. Each descriptor includes a 'garbage/other' class.
    - **ex. 1** (N = 4) : Y1 = [Y1_1 : lexical signs (categorical with 4 different signs), Y1_2 : pointing signs, Y1_3 : depicting signs, Y1_4 : fragment buoys]
    - **ex. 2** (N = 2) : Y2 = [Y2_1 : pointing signs to PRO1/2/3, Y2_2 : lexical signs (all)]
    - **ex. 3** (N = 2) : Y3 = [Y3_1 : pointing signs to PRO1/2/3, Y3_2 : depicting signs A/G]
    - **ex. 4** (N = 1) : Y4 = [Y4_1 : depicting signs]
- sign types, i.e. the most probable sign type for each frame. In this case, lexical signs are seen as binary.
    - **ex. 5**: Y5 = [other, lexical signs,  pointing signs, depicting signs, fragment buoys]. 
    - **ex. 6**: Y6 = [other, depicting signs] : this should give the same results as ex. 4

## Getting help on a function

In [2]:
# Use help(function_name)
# For instance:

help(get_raw_annotation_from_file)

Help on function get_raw_annotation_from_file in module src.models.data_utils:

get_raw_annotation_from_file(corpus, from_notebook=False)
    Gets raw annotation from data file
    
    Inputs:
        corpus: 'DictaSign' or 'NCSLGR'
        from_notebook: True if used in Jupyter notebook
    
    Outputs:
        Annotation data



## Main helper function for data handling (`data_utils.py`): `get_data_concatenated`

This is the main function, which enables to extract data in usable format for training.

`get_data_concatenated` returns [X_features, X_frames], Y, idx_trueData or [X_features, X_frames], Y (depending on return_idx_trueData)

#### Outputs
- **X_features** is a numpy array of size [1, total_time_steps, features_number] containing all retained preprocessed features for all retained frames
- **X_frames** is simply a list of paths for all retained frames (frames cannot be stored in memory directly, and will have to be read during training thanks to frames paths)
- **Y** is the annotation data (i.e. ground truth data) in the desired format

#### Inputs
- **corpus** (string)
- **output_form**:
    - 'mixed' if different and separated Outputs
    - 'sign_types' if annotation is only a binary matrix of sign types
- **types**: a list of lists of original names that are used to compose final outputs
- **nonZero**: a list of lists of nonzero values to consider. If 4 outputs with all nonZero values should be considered, nonZero=[[],[],[],[]]
- **binary**: only considered when output_form=mixed. It's a list (True/False) indicating whether the values should be categorical or binary
- **features_dict**: a dictionary indication which features to keep ; e.g.: {'features_HS':np.arange(0, 420), 'features_HS_norm':np.array([]), 'raw':np.array([]), 'raw_norm':np.array([])}
- **preloaded_features**: if features are already loaded, in the format of a list (features for each video)
- **provided_annotation**: raw annotation data (not needed)
- **video_indices**: numpy array for a list of videos
- **separation**: in order to separate consecutive videos
- **from_notebook**: if notebook script, data is in parent folder
- **return_idx_trueData**: if True, returns a binary vector with 0 where separations are
- **features_type**: 'features', 'frames', 'both'            
- **frames_path_before_video**: video frames are supposed to be in folders, like '/localHD/DictaSign/convert/img/DictaSign_lsf_S7_T2_A10',
- **empty_image_path**: path of a white frame


## Main helper function for model handling (`model_utils.py`): `get_model`

This is the main function, which enables to obtain the Keras model.

`get_model` returns a Keras model

#### Outputs
- a Keras model

#### Inputs
- **output_names**: list of outputs (strings)
- **output_classes**: list of number of classes of each output type
- **output_weights**: list of weights for each_output
- **conv** (bool): if True, applies convolution on input
- **conv_filt**: number of convolution filters
- **conv_ker**: size of convolution kernel
- **conv_strides**: size of convolution strides
- **rnn_number**: number of recurrent layers
- **rnn_type**: type of recurrent layers (string)
- **rnn_hidden_units**: number of hidden units
- **dropout**: how much dropout (0 to 1)
- **att_in_rnn**: if True, applies attention layer before recurrent layers
- **att_in_rnn_single**: single (shared) attention layer or not
- **att_in_rnn_type** (string): timewise or featurewise attention layer
- **att_out_rnn**: if True, applies attention layer after recurrent layers
- **att_out_rnn_single**: single (shared) attention layer or not
- **att_out_rnn_type** (string): timewise or featurewise attention layer
- **rnn_return_sequences**: if False, only last timestep of recurrent layers is returned
- **classif_local** (bool): whether classification is for each timestep (local) of globally for the sequence
- **mlp_layers_number**: number of additional dense layers
- **mlp_layers_size**: size of additional dense layers
- **optimizer**: gradient optimizer type (string)
- **learning_rate**: learning rate (float)
- **time_steps**: length of sequences (int)
- **features_number**: number of features (int)
- **features_type**: 'features' (1D vector of features), 'frames' (for a CNN processing) or 'both'
- **img_height** and **img_width**: size of CNN input
- **cnnType**: 'resnet', 'vgg' or 'mobilenet'
- **cnnFirstTrainedLayer**: index of first trainable layer in CNN (int)
- **cnnReduceDim**: if greater than 0, size of CNN flattened output is reduced to cnnReduceDim
- **print_summary** (bool)

## Shortcut: script to recognize a unique output on DictaSign

Just use `python src/recognitionUniqueDictaSignFromScript.py`

Provided help:

In [3]:
!python ../src/recognitionUniqueDictaSignFromScript.py -h

usage: recognitionUniqueDictaSignFromScript.py [-h] [--outputName OUTPUTNAME]
                                               [--flsBinary {0,1}]
                                               [--flsKeep [FLSKEEP [FLSKEEP ...]]]
                                               [--comment COMMENT]
                                               [--videoSplitMode {manual,auto}]
                                               [--fractionValid FRACTIONVALID]
                                               [--fractionTest FRACTIONTEST]
                                               [--signerIndependent {0,1}]
                                               [--taskIndependent {0,1}]
                                               [--excludeTask9 {0,1}]
                                               [--tasksTrain [{1,2,3,4,5,6,7,8,9} [{1,2,3,4,5,6,7,8,9} ...]]]
                                               [--tasksValid [{1,2,3,4,5,6,7,8,9} [{1,2,3,4,5,6,7,8,9} ...]]]
                               

  --tasksTrain [{1,2,3,4,5,6,7,8,9} [{1,2,3,4,5,6,7,8,9} ...]]
                        Training task indices
  --tasksValid [{1,2,3,4,5,6,7,8,9} [{1,2,3,4,5,6,7,8,9} ...]]
                        Validation task indices
  --tasksTest [{1,2,3,4,5,6,7,8,9} [{1,2,3,4,5,6,7,8,9} ...]]
                        Test task indices
  --signersTrain [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} ...]]
                        Training signer indices
  --signersValid [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} ...]]
                        Validation signer indices
  --signersTest [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} ...]]
                        Test signer indices
  --idxTrainBypass [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69

A few examples:

* `python src/recognitionUniqueDictaSignFromScript.py --outputName DS` to select DS as output
* `python src/recognitionUniqueDictaSignFromScript.py --outputName fls --flsBinary 1` to select binary FLS as output
* `python src/recognitionUniqueDictaSignFromScript.py --outputName fls --flsBinary 0 --flsKeep 41891 43413 43422 42992` to select categorical FLS as output, with 4 signs
* `python src/recognitionUniqueDictaSignFromScript.py --outputName DS --inputType 2Draw` to select 2D raw input preprocessed features
* `python src/recognitionUniqueDictaSignFromScript.py --outputName DS --inputFeaturesFrames frames` to select only frames as input (CNN)

## Building data and model together, manually

In these examples we analyze the different types of output form Y

In [4]:
# let us split train/valid/test videos
# In this case we split by signers in a manual fashion

idxTrain, idxValid, idxTest = getVideoIndicesSplitDictaSign(tasksTrain=[],
                                                            tasksValid=[],
                                                            tasksTest=[],
                                                            signersTrain=[0,1,2,3,4,5,6,7,8,9],
                                                            signersValid=[10,11,12],
                                                            signersTest=[13,14,15],
                                                            excludeTask9=False,
                                                            videoSplitMode='manual',
                                                            checkSplits=True,
                                                            checkSets=True,
                                                            from_notebook=True)
print(idxTrain)

Number of videos:
Train: 66
Valid: 10
Test: 18
Total: 94
[20 60 55 25 41  1 52 64 16  5 18 37 13 14 22 15 17  4 48 63 62 65 23  3
 40 57 35 56 49 53 42 44  9 51 33  6 19 38 26  2  0 10 39 12 34 61 36 11
 46 30 32 45 31 24 43 21 27 50 59 47 28  7 58  8 54 29]


In [5]:
# Getting a dictionary for desired preprocessed features
# In this case we ask for normalized 3Dfeatures_HS (this correspond to a total number of 420 features):

features_dict, features_number = getFeaturesDict(inputType='3Dfeatures_HS', inputNormed=True)

print(features_dict)
print(features_number)

{'features_HS': array([], dtype=float64), 'features_HS_norm': array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
  

### First category of examples: `output_form = 'mixed'` (examples 1 to 4)

#### ex. 1 :

##### Data

In [6]:
import csv

idGloss = {}

with open('Dicta-Sign-LSF_ID.csv', newline='') as csvfile:
    glossreader = csv.reader(csvfile, delimiter=';', quotechar='|')
    for row in glossreader:
        idGloss[row[0]] = row[1]

In [7]:
# we only consider 4 lexical signs, indices 41891,43413,43422,42992

flsKept = [41891,43413,43422,42992]
N_fls = len(flsKept)

# that correspond to glosses:

for i in flsKept:
    print(idGloss[str(i)])

PARIS3 (TOUR EIFFEL):NS
RESTAURANT
QUALITE-DE GRANDE /EXCELLENT
VISITER1:VAR


In [8]:
[X_feat_train_1, X_frames_train_1], Y_train_1 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            types=[['fls'], ['DS'], ['PT'], ['FBUOY']],
                            nonZero=[flsKept, [], [], []],
                            binary=[False, True, True, True],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [9]:
print(X_feat_train_1.shape)
print(X_frames_train_1.shape)
print(len(Y_train_1))

(1, 665612, 420)
(665612,)
4


As can be seen above, X_feat is a big matrix storing all 420 preprocessed features for each frame. We can print the first 15 features for frame number 192:

In [10]:
print(X_feat_train_1[0,192,0:15])

[7.77103379e-02 3.65124324e-05 1.85295687e-06 1.93622327e-06
 1.13211843e-06 4.25406470e-05 3.49091715e-04 1.35046095e-04
 8.68812094e-07 5.24199140e-06 1.28622287e-05 8.67029369e-01
 1.05695959e-04 5.40188551e-02 3.49314945e-07]


X_frames stores paths for all frames:

In [11]:
X_frames_train_1[192]

'/localHD/DictaSign/convert/img/DictaSign_lsf_S3_T4_A2_front/00193.jpg'

Y_train stores the 4 linguistic descriptors annotation:

In [12]:
print(Y_train_1[0].shape)
print(Y_train_1[1].shape)
print(Y_train_1[2].shape)
print(Y_train_1[3].shape)

(1, 665612, 5)
(1, 665612, 2)
(1, 665612, 2)
(1, 665612, 2)


In [13]:
# First depicting frame:
i_DS_one = np.where(Y_train_1[1][0,:,1]==1)[0][0]
print(i_DS_one)

7940


In [14]:
print(Y_train_1[0][0,i_DS_one,:])
print(Y_train_1[1][0,i_DS_one,:])
print(Y_train_1[2][0,i_DS_one,:])
print(Y_train_1[3][0,i_DS_one,:])

[1. 0. 0. 0. 0.]
[0. 1.]
[1. 0.]
[0. 1.]


Frame 192 is annotated as non-lexical, depicting, non-pointing, non-fbuoy

##### Model

In [15]:
# training model can be built to take preprocessed features as input, frames as input or both
model_1_features = get_model(output_names=['fls', 'DS', 'PT', 'FBUOY'],
                    output_classes=[N_fls+1,2,2,2],
                    output_weights=[1,1,1,1],
                    features_number=features_number,
                    features_type='features')

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, 100, 200)     252200      input_1[0][0]                    
__________________________________________________________________________________________________
bidirectional (Bidirectional)   (None, 100, 110)     112640      conv1d[0][0]                     
__________________________________________________________________________________________________
bidirectional_1 (Bidirectional) (None, 100, 110)     73040       bidirectional[0][0]              
______________________________________________________________________________________________

In [16]:
model_1_frames = get_model(output_names=['fls', 'DS', 'PT', 'FBUOY'],
                    output_classes=[N_fls+1,2,2,2],
                    output_weights=[1,1,1,1],
                    features_number=features_number,
                    features_type='frames')

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 100, 224, 22 0                                            
__________________________________________________________________________________________________
time_distributed_4 (TimeDistrib (None, 100, 2048)    23587712    input_2[0][0]                    
__________________________________________________________________________________________________
bidirectional_2 (Bidirectional) (None, 100, 110)     925760      time_distributed_4[0][0]         
__________________________________________________________________________________________________
bidirectional_3 (Bidirectional) (None, 100, 110)     73040       bidirectional_2[0][0]            
____________________________________________________________________________________________

In [17]:
model_1_both = get_model(output_names=['fls', 'DS', 'PT', 'FBUOY'],
                    output_classes=[N_fls+1,2,2,2],
                    output_weights=[1,1,1,1],
                    features_number=features_number,
                    features_type='both')

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
input_5 (InputLayer)            [(None, 100, 224, 22 0                                            
__________________________________________________________________________________________________
conv1d_1 (Conv1D)               (None, 100, 200)     252200      input_4[0][0]                    
__________________________________________________________________________________________________
time_distributed_9 (TimeDistrib (None, 100, 2048)    23587712    input_5[0][0]                    
____________________________________________________________________________________________

#### ex. 2 :

##### Data

In [18]:
# in this example, data from 3 channels (PT_PRO1, 2 and 3) are assembled to form a new category, 
# and a second category corresponds to all lexical signs (binary)
[X_feat_train_2, X_frames_train_2], Y_train_2 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            types=[['PT_PRO1','PT_PRO2', 'PT_PRO3'], ['fls']],
                            nonZero=[[],[]],
                            binary=[True,True],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [19]:
print(X_feat_train_2.shape)
print(X_frames_train_2.shape)
print(len(Y_train_2))

(1, 665612, 420)
(665612,)
2


In [20]:
print(Y_train_2[0].shape)
print(Y_train_2[1].shape)

(1, 665612, 2)
(1, 665612, 2)


##### Model

In [21]:
# using only preprocessed features as input:
model_2_features = get_model(output_names=['pointing-signs-pro123', 'lexical'],
                    output_classes=[2,2],
                    output_weights=[1,1],
                    features_number=features_number,
                    features_type='features')

Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
conv1d_2 (Conv1D)               (None, 100, 200)     252200      input_7[0][0]                    
__________________________________________________________________________________________________
bidirectional_6 (Bidirectional) (None, 100, 110)     112640      conv1d_2[0][0]                   
__________________________________________________________________________________________________
bidirectional_7 (Bidirectional) (None, 100, 110)     73040       bidirectional_6[0][0]            
____________________________________________________________________________________________

#### ex. 3 :

##### Data

In [22]:
# in this example, data from 3 channels (PT_PRO1, 2 and 3) are assembled to form a new category
# and data from 2 channels (DSA, DSG) are assembled to form a second category
[X_feat_train_3, X_frames_train_3], Y_train_3 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            types=[['PT_PRO1','PT_PRO2', 'PT_PRO3'], ['DSA', 'DSG']],
                            nonZero=[[],[]],
                            binary=[True,True],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [23]:
print(X_feat_train_3.shape)
print(X_frames_train_3.shape)
print(len(Y_train_3))

(1, 665612, 420)
(665612,)
2


In [24]:
print(Y_train_3[0].shape)
print(Y_train_3[1].shape)

(1, 665612, 2)
(1, 665612, 2)


##### Model

In [25]:
# using only preprocessed features as input:
model_3_features = get_model(output_names=['pointing-signs-pro123', 'depicting-signs-AG'],
                    output_classes=[2, 2],
                    output_weights=[1, 1],
                    features_number=features_number,
                    features_type='features')

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_8 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
conv1d_3 (Conv1D)               (None, 100, 200)     252200      input_8[0][0]                    
__________________________________________________________________________________________________
bidirectional_8 (Bidirectional) (None, 100, 110)     112640      conv1d_3[0][0]                   
__________________________________________________________________________________________________
bidirectional_9 (Bidirectional) (None, 100, 110)     73040       bidirectional_8[0][0]            
____________________________________________________________________________________________

#### ex. 4 :

##### Data

In [26]:
# in this example, only depicting signs as output
[X_feat_train_4, X_frames_train_4], Y_train_4 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            types=[['DS']],
                            nonZero=[[]],
                            binary=[True],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [27]:
print(X_feat_train_4.shape)
print(X_frames_train_4.shape)
print(len(Y_train_4))

(1, 665612, 420)
(665612,)
1


In [28]:
print(Y_train_4[0].shape)
print(np.sum(Y_train_4[0],axis=1))

(1, 665612, 2)
[[623477.  42135.]]


##### Model

In [29]:
# using only preprocessed features as input:
model_4_features = get_model(output_names=['DS'],
                    output_classes=[2],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_10 (Bidirectio (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_11 (Bidirectio (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_18 (TimeDis (None, 100, 2)            222       
Total params: 438,102
Trainable params: 438,102
Non-trainable params: 0
_________________________________________________________________


### Second category of examples: `output_form = 'sign_types'` (examples 5 and 6)

#### ex. 5 :

##### Data

In [30]:
[X_feat_train_5, X_frames_train_5], Y_train_5 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='sign_types',
                            types=[['fls'],['DS'],['PT'],['FBUOY']],
                            nonZero=[[],[],[],[]],
                            binary=[],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [31]:
print(X_feat_train_5.shape)
print(X_frames_train_5.shape)
print(Y_train_5.shape) # when output_form='sign_types', Y is not a list, but a matrix

(1, 665612, 420)
(665612,)
(1, 665612, 5)


In [32]:
#print(Y_train_5[0,0:200,:])
print(np.sum(Y_train_5,axis=1))

[[488403. 126592.  42135.  15146.   9260.]]


##### Model

In [33]:
# using only preprocessed features as input:
model_5_features = get_model(output_names=['fls-DS-PT-FBUOY'],
                    output_classes=[5],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_12 (Bidirectio (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_13 (Bidirectio (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_19 (TimeDis (None, 100, 5)            555       
Total params: 438,435
Trainable params: 438,435
Non-trainable params: 0
_________________________________________________________________


#### ex. 6 :

##### Data

In [34]:
[X_feat_train_6, X_frames_train_6], Y_train_6 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='sign_types',
                            types=[['DS']],
                            nonZero=[[]],
                            binary=[],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [35]:
print(X_feat_train_6.shape)
print(X_frames_train_6.shape)
print(Y_train_6.shape) # when output_form='sign_types', Y is not a list, but a matrix

(1, 665612, 420)
(665612,)
(1, 665612, 2)


In [36]:
print(Y_train_6[0,1000:1020,:])
print(np.sum(Y_train_6,axis=1))

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
[[623477.  42135.]]


##### Model

In [37]:
# using only preprocessed features as input:
model_6_features = get_model(output_names=['DS'],
                    output_classes=[2],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_14 (Bidirectio (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_15 (Bidirectio (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_20 (TimeDis (None, 100, 2)            222       
Total params: 438,102
Trainable params: 438,102
Non-trainable params: 0
_________________________________________________________________


## Training the models

Now we look at how to train the models

In [38]:
batch_size=100
epochs=10
seq_length=100

In [39]:
[X_feat_valid_1, X_frames_valid_1], Y_valid_1 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            types=[['fls'], ['DS'], ['PT'], ['FBUOY']],
                            nonZero=[flsKept, [], [], []],
                            binary=[False, True, True, True],
                            video_indices=idxValid,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [40]:
history = train_model(model_1_features,
                      [X_feat_train_1, X_frames_train_1],
                      Y_train_1,
                      [X_feat_valid_1, X_frames_valid_1],
                      Y_valid_1,
                      batch_size=batch_size,
                      epochs=epochs,
                      seq_length=seq_length)

Instructions for updating:
Please use Model.fit, which supports generators.
Train for 67.0 steps, validate for 1 steps
Epoch 1/10
67/67 [==============================] - 64s 953ms/step - loss: 0.4188 - time_distributed_loss: 0.0302 - time_distributed_1_loss: 0.2120 - time_distributed_2_loss: 0.1013 - time_distributed_3_loss: 0.0754 - time_distributed_acc: 0.9931 - time_distributed_1_acc: 0.9303 - time_distributed_2_acc: 0.9773 - time_distributed_3_acc: 0.9741 - val_loss: 0.4073 - val_time_distributed_loss: 3.1295e-04 - val_time_distributed_1_loss: 0.2865 - val_time_distributed_2_loss: 0.0742 - val_time_distributed_3_loss: 0.0463 - val_time_distributed_acc: 1.0000 - val_time_distributed_1_acc: 0.9258 - val_time_distributed_2_acc: 0.9851 - val_time_distributed_3_acc: 0.9926
Epoch 2/10
67/67 [==============================] - 68s 1s/step - loss: 0.2941 - time_distributed_loss: 0.0078 - time_distributed_1_loss: 0.1605 - time_distributed_2_loss: 0.0837 - time_distributed_3_loss: 0.0421 - t

In [41]:
history

{'loss': [0.4188355069551895,
  0.29405344978197295,
  0.3492838567984638,
  0.2432987969646703,
  0.2833965250582837,
  0.2967764120270957,
  0.2480675568109128,
  0.2540619052501757,
  0.2245526415254198,
  0.2113249334437189],
 'time_distributed_loss': [0.03018735,
  0.007830408,
  0.007923277,
  0.007105666,
  0.004239243,
  0.007056573,
  0.005081094,
  0.0070459717,
  0.0038447264,
  0.0030796758],
 'time_distributed_1_loss': [0.21202528,
  0.16045696,
  0.18310556,
  0.12823848,
  0.14958774,
  0.16597302,
  0.13019404,
  0.13808586,
  0.116900966,
  0.11659155],
 'time_distributed_2_loss': [0.10126622,
  0.08370611,
  0.090308815,
  0.07282035,
  0.08038396,
  0.07318296,
  0.06660915,
  0.0689124,
  0.06527522,
  0.059076786],
 'time_distributed_3_loss': [0.07535666,
  0.04205994,
  0.06794621,
  0.03513429,
  0.049185596,
  0.050563883,
  0.046183236,
  0.04001767,
  0.03853174,
  0.032576922],
 'time_distributed_acc': [0.9931493,
  0.99911195,
  0.9990836,
  0.99914926,
  0.

In [43]:
Y_train_6.shape

(1, 665612, 2)

In [47]:
np.sum(Y_train_4[0],axis=1)

array([[623477.,  42135.]], dtype=float32)

In [48]:
np.sum(Y_train_6,axis=1)

array([[623477.,  42135.]])

In [50]:
np.sum(np.abs(Y_train_4[0]-Y_train_6))

0.0