# Stats on annotations

In [1]:
# imports
import numpy as np
import itertools as it
from tqdm import tqdm
from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [3]:
# load data
annot = np.load('../data/processed/DictaSign/annotations.npz', encoding='latin1', allow_pickle=True)
print(annot.files)
nV = len(annot['dataBrut_fls']) # 94
listeV = np.load('../data/processed/DictaSign/list_videos.npy', encoding='latin1')
nTasks = 9

def getSessionVideo(videoIdx):
    return int(listeV[videoIdx][1])
def getTaskVideo(videoIdx):
    return int(listeV[videoIdx][4])
def getSignerVideo(videoIdx):
    return listeV[videoIdx][6:]
def getUniqueSigners():
    signersTotal = []
    for i in range(nV):
        signersTotal.append(getSignerVideo(i))
    return np.unique(np.array(signersTotal))
def valuesCount(vector):
    values = [i[0] for i in it.groupby(list(vector))]
    count = [len(list(group)) for _, group in it.groupby(list(vector))]
    return values, count
def countUnitsFrames(vector):
    totalUnits = 0
    totalFrames = 0
    values, count = valuesCount(vector)
    nUnits = len(values)
    for i in range(nUnits):
        if values[i] > 0:
            totalUnits += 1
            totalFrames += count[i]
    return totalUnits, totalFrames

idxUniqueSigners = getUniqueSigners()
nSigners = idxUniqueSigners.shape[0]

listCategories = ['fls', 'DS', 'PT', 'FBUOY', 'N', 'FS']
idxCategories = [0,9,1,17,18,19]
nCategories = len(listCategories)

listCategoriesDS = ['DSL', 'DSM', 'DSS', 'DSG', 'DSA', 'DST', 'DSX']
idxCategoriesDS = [12,13,14,11,10,15,16]
nCategoriesDS = len(listCategoriesDS)

['dataBrut_fls', 'dataBrut_PT', 'dataBrut_PT_PRO1', 'dataBrut_PT_PRO2', 'dataBrut_PT_PRO3', 'dataBrut_PT_LOC', 'dataBrut_PT_DET', 'dataBrut_PT_LBUOY', 'dataBrut_PT_BUOY', 'dataBrut_DS', 'dataBrut_DSA', 'dataBrut_DSG', 'dataBrut_DSL', 'dataBrut_DSM', 'dataBrut_DSS', 'dataBrut_DST', 'dataBrut_DSX', 'dataBrut_FBUOY', 'dataBrut_N', 'dataBrut_FS']


In [4]:
tot=0
for i in range(nV):
    tot += annot['dataBrut_fls'][i].shape[0]
print(tot)
print(tot*40/1000/3600)

1007593
11.195477777777779


In [5]:
[i[0] for i in it.groupby(list(annot['dataBrut_fls'][0][:,0]))]

[0,
 42495,
 0,
 42856,
 0,
 42093,
 0,
 42814,
 0,
 42159,
 0,
 42856,
 0,
 43368,
 0,
 43122,
 0,
 42503,
 0,
 43015,
 0,
 42628,
 0,
 42319,
 0,
 42827,
 0,
 42418,
 0,
 43614,
 0,
 42072,
 0,
 42418,
 0,
 41852,
 0,
 41884,
 0,
 43403,
 0,
 42319,
 0,
 43470,
 0,
 42827,
 0,
 42985,
 0,
 43470,
 0,
 42347,
 0,
 43131,
 0,
 43101,
 0,
 43430,
 0,
 43359,
 0,
 42109,
 0,
 42616,
 0,
 41893,
 0,
 42719,
 0,
 42072,
 0,
 42127,
 0,
 42104,
 0,
 42628,
 0,
 42208,
 0,
 41827,
 42557,
 0,
 42827,
 0,
 43327,
 43363,
 0,
 42124,
 0,
 42072,
 0,
 42543,
 0,
 42827,
 0,
 42151,
 0,
 43403,
 0,
 42319,
 0,
 43543,
 0,
 42017,
 0,
 41916,
 0,
 41827,
 0,
 42104,
 0,
 42104,
 0,
 42104,
 0,
 43470,
 0,
 43268,
 0,
 43679,
 0,
 43015,
 0,
 43252,
 0,
 43015,
 0,
 42719,
 0,
 43131,
 0,
 43363,
 0,
 42072,
 0,
 42127,
 0,
 43498,
 0,
 43363,
 0,
 42124,
 0,
 42072,
 0,
 43131,
 0,
 42264,
 0,
 42616,
 0,
 41893,
 0,
 42543,
 0,
 42318,
 0,
 41764,
 42557,
 0,
 42013,
 0,
 43015,
 0,
 43015,
 0,


In [ ]:
fls = []
for iV in range(nV):
    fls = fls + [i[0] for i in it.groupby(list(annot['dataBrut_fls'][iV][:,0]))]

uniq, counts = np.unique(fls, return_counts=True)
uniq = uniq[1:]
counts = counts[1:]

print(len(uniq))
print(uniq)    # ['a' 'b']
print(counts)  # [2 3]
print(np.max(counts))
np.savetxt('savedData/flscounts.csv', counts, delimiter=',')
a,b=np.histogram(counts, bins=np.arange(0,900,1))

In [16]:
t = np.sum(a[1:401])
print(t)
print(2081-t)

2080
1


In [183]:
a=0
b=0
for i in range(nV):
    aTmp, bTmp = countUnitsFrames(annot['dataBrut_fls'][i].flatten())
    a+=aTmp
    b+=bTmp

In [160]:
for i in range(nCategories):
    print(annot.files[idxCategories[i]])


dataBrut_fls
dataBrut_DS
dataBrut_PT
dataBrut_FBUOY
dataBrut_N
dataBrut_FS


In [254]:
tabCategoriesSignersUnitsFrames = np.zeros((nSigners, nCategories, 2))
tabCategoriesDSSignersUnitsFrames = np.zeros((nSigners, nCategoriesDS, 2))

for iSigner in tqdm(range(nSigners)):
    for iCategory in range(nCategories):
        units = 0
        frames = 0
        for iVideo in range(nV):
            signerIdxVideo = getSignerVideo(iVideo)
            if signerIdxVideo == idxUniqueSigners[iSigner]:
                unitsTmp, framesTmp = countUnitsFrames(annot['dataBrut_'+listCategories[iCategory]][iVideo].flatten())
                units += unitsTmp
                frames += framesTmp
        tabCategoriesSignersUnitsFrames[iSigner, iCategory, 0] = units
        tabCategoriesSignersUnitsFrames[iSigner, iCategory, 1] = frames
    for iCategoryDS in range(nCategoriesDS):
        units = 0
        frames = 0
        for iVideo in range(nV):
            signerIdxVideo = getSignerVideo(iVideo)
            if signerIdxVideo == idxUniqueSigners[iSigner]:
                unitsTmp, framesTmp = countUnitsFrames(annot['dataBrut_'+listCategoriesDS[iCategoryDS]][iVideo].flatten())
                units += unitsTmp
                frames += framesTmp
        tabCategoriesDSSignersUnitsFrames[iSigner, iCategoryDS, 0] = units
        tabCategoriesDSSignersUnitsFrames[iSigner, iCategoryDS, 1] = frames

tabCategoriesTasksUnitsFrames = np.zeros((nTasks, nCategories, 2))
tabCategoriesDSTasksUnitsFrames = np.zeros((nTasks, nCategoriesDS, 2))

for iTask in tqdm(range(nTasks)):
    for iCategory in range(nCategories):
        units = 0
        frames = 0
        for iVideo in range(nV):
            taskIdxVideo = getTaskVideo(iVideo)-1
            if taskIdxVideo == iTask:
                unitsTmp, framesTmp = countUnitsFrames(annot['dataBrut_'+listCategories[iCategory]][iVideo].flatten())
                units += unitsTmp
                frames += framesTmp
        tabCategoriesTasksUnitsFrames[iTask, iCategory, 0] = units
        tabCategoriesTasksUnitsFrames[iTask, iCategory, 1] = frames
    for iCategoryDS in range(nCategoriesDS):
        units = 0
        frames = 0
        for iVideo in range(nV):
            taskIdxVideo = getTaskVideo(iVideo)-1
            if taskIdxVideo == iTask:
                unitsTmp, framesTmp = countUnitsFrames(annot['dataBrut_'+listCategoriesDS[iCategoryDS]][iVideo].flatten())
                units += unitsTmp
                frames += framesTmp
        tabCategoriesDSTasksUnitsFrames[iTask, iCategoryDS, 0] = units
        tabCategoriesDSTasksUnitsFrames[iTask, iCategoryDS, 1] = frames



  0%|          | 0/16 [00:00<?, ?it/s]

  6%|▋         | 1/16 [00:03<00:53,  3.60s/it]

 12%|█▎        | 2/16 [00:04<00:39,  2.86s/it]

 19%|█▉        | 3/16 [00:07<00:37,  2.91s/it]

 25%|██▌       | 4/16 [00:10<00:35,  2.94s/it]

 31%|███▏      | 5/16 [00:13<00:32,  2.95s/it]

 38%|███▊      | 6/16 [00:15<00:25,  2.50s/it]

 44%|████▍     | 7/16 [00:16<00:19,  2.22s/it]

 50%|█████     | 8/16 [00:18<00:16,  2.00s/it]

 56%|█████▋    | 9/16 [00:21<00:16,  2.33s/it]

 62%|██████▎   | 10/16 [00:22<00:12,  2.10s/it]

 69%|██████▉   | 11/16 [00:26<00:12,  2.49s/it]

 75%|███████▌  | 12/16 [00:29<00:11,  2.77s/it]

 81%|████████▏ | 13/16 [00:30<00:06,  2.29s/it]

 88%|████████▊ | 14/16 [00:32<00:04,  2.07s/it]

 94%|█████████▍| 15/16 [00:33<00:01,  1.71s/it]

100%|██████████| 16/16 [00:36<00:00,  2.29s/it]


  0%|          | 0/9 [00:00<?, ?it/s]

 11%|█         | 1/9 [00:04<00:32,  4.05s/it]

 22%|██▏       | 2/9 [00:08<00:29,  4.15s/it]

 33%|███▎      | 3/9 [00:12<00:25,  4.22s/it]

 4

In [262]:
#np.savetxt('savedData/signers.csv', np.array(idxUniqueSigners), delimiter=',')

print(listCategories)
print(np.sum(tabCategoriesSignersUnitsFrames[:,:,0],axis=0))
print(np.sum(tabCategoriesSignersUnitsFrames[:,:,1],axis=0))


['fls', 'DS', 'PT', 'FBUOY', 'N', 'FS']
[12.00898912  1.75370069  1.7632834   0.31032113  0.10484106  0.05886459]
[10.63332554  3.09377072  1.10881245  0.7379951   0.28410007  0.14199612]


In [255]:
np.savetxt('savedData/tabCategoriesUnits.csv', np.sum(tabCategoriesSignersUnitsFrames[:,:,0],axis=0), delimiter=',')
np.savetxt('savedData/tabCategoriesFrames.csv', np.sum(tabCategoriesSignersUnitsFrames[:,:,1],axis=0), delimiter=',')

tabCategoriesSignersUnitsTotal = np.tile(np.sum(tabCategoriesSignersUnitsFrames[:,:,0],axis=1),(nCategories,1)).transpose()
tabCategoriesSignersFramesTotal = np.tile(np.sum(tabCategoriesSignersUnitsFrames[:,:,1],axis=1),(nCategories,1)).transpose()

tabCategoriesSignersUnitsFrames[:,:,0]/=tabCategoriesSignersUnitsTotal
tabCategoriesSignersUnitsFrames[:,:,1]/=tabCategoriesSignersFramesTotal

np.savetxt('savedData/tabCategoriesUnitsNorm.csv', np.sum(tabCategoriesSignersUnitsFrames[:,:,0],axis=0), delimiter=',')
np.savetxt('savedData/tabCategoriesFramesNorm.csv', np.sum(tabCategoriesSignersUnitsFrames[:,:,1],axis=0), delimiter=',')

np.savetxt('savedData/tabCategoriesSignersUnitsNormComplet.csv', tabCategoriesSignersUnitsFrames[:,:,0], delimiter=',')
np.savetxt('savedData/tabCategoriesSignersFramesNormComplet.csv', tabCategoriesSignersUnitsFrames[:,:,1], delimiter=',')

#for iSigner in range(nSigners):
#    np.savetxt('savedData/tabCategoriesSigner'+idxUniqueSigners[iSigner]+'UnitsNorm.csv', tabCategoriesSignersUnitsFrames[iSigner,:,0], delimiter=',')
#    np.savetxt('savedData/tabCategoriesSigner'+idxUniqueSigners[iSigner]+'FramesNorm.csv', tabCategoriesSignersUnitsFrames[iSigner,:,1], delimiter=',')

['fls', 'DS', 'PT', 'FBUOY', 'N', 'FS']
[24565.  3606.  3651.   589.   155.   118.]
[205530.  60794.  23045.  14359.   3830.   2490.]


In [256]:
print(listCategoriesDS)
print(np.sum(tabCategoriesDSSignersUnitsFrames[:,:,0],axis=0))
print(np.sum(tabCategoriesDSSignersUnitsFrames[:,:,1],axis=0))

np.savetxt('savedData/tabCategoriesDSUnits.csv', np.sum(tabCategoriesDSSignersUnitsFrames[:,:,0],axis=0), delimiter=',')
np.savetxt('savedData/tabCategoriesDSFrames.csv', np.sum(tabCategoriesDSSignersUnitsFrames[:,:,1],axis=0), delimiter=',')

tabCategoriesDSSignersUnitsTotal = np.tile(np.sum(tabCategoriesDSSignersUnitsFrames[:,:,0],axis=1),(nCategoriesDS,1)).transpose()
tabCategoriesDSSignersFramesTotal = np.tile(np.sum(tabCategoriesDSSignersUnitsFrames[:,:,1],axis=1),(nCategoriesDS,1)).transpose()

tabCategoriesDSSignersUnitsFrames[:,:,0]/=tabCategoriesDSSignersUnitsTotal
tabCategoriesDSSignersUnitsFrames[:,:,1]/=tabCategoriesDSSignersFramesTotal

np.savetxt('savedData/tabCategoriesDSUnitsNorm.csv', np.sum(tabCategoriesDSSignersUnitsFrames[:,:,0],axis=0), delimiter=',')
np.savetxt('savedData/tabCategoriesDSFramesNorm.csv', np.sum(tabCategoriesDSSignersUnitsFrames[:,:,1],axis=0), delimiter=',')

['DSL', 'DSM', 'DSS', 'DSG', 'DSA', 'DST', 'DSX']
[1389. 1170.  535.  581.  590.  310.   41.]
[22725. 16378.  7044. 16286.  9056.  5081.   626.]


In [257]:
print(listCategories)
print(np.sum(tabCategoriesTasksUnitsFrames[:,:,0],axis=0))
print(np.sum(tabCategoriesTasksUnitsFrames[:,:,1],axis=0))

tabCategoriesTasksUnitsTotal = np.tile(np.sum(tabCategoriesTasksUnitsFrames[:,:,0],axis=1),(nCategories,1)).transpose()
tabCategoriesTasksFramesTotal = np.tile(np.sum(tabCategoriesTasksUnitsFrames[:,:,1],axis=1),(nCategories,1)).transpose()

tabCategoriesTasksUnitsFrames[:,:,0]/=tabCategoriesTasksUnitsTotal
tabCategoriesTasksUnitsFrames[:,:,1]/=tabCategoriesTasksFramesTotal

np.savetxt('savedData/tabCategoriesTasksUnitsNormComplet.csv', tabCategoriesTasksUnitsFrames[:,:,0], delimiter=',')
np.savetxt('savedData/tabCategoriesTasksFramesNormComplet.csv', tabCategoriesTasksUnitsFrames[:,:,1], delimiter=',')

#for iTask in range(nTasks):
#    np.savetxt('savedData/tabCategoriesTasks'+str(iTask)+'UnitsNorm.csv', tabCategoriesTasksUnitsFrames[iTask,:,0], delimiter=',')
#    np.savetxt('savedData/tabCategoriesTasks'+str(iTask)+'FramesNorm.csv', tabCategoriesTasksUnitsFrames[iTask,:,1], delimiter=',')

['fls', 'DS', 'PT', 'FBUOY', 'N', 'FS']
[24565.  3606.  3651.   589.   155.   118.]
[205530.  60794.  23045.  14359.   3830.   2490.]


In [258]:
print(listCategoriesDS)
print(np.sum(tabCategoriesDSTasksUnitsFrames[:,:,0],axis=0))
print(np.sum(tabCategoriesDSTasksUnitsFrames[:,:,1],axis=0))

['DSL', 'DSM', 'DSS', 'DSG', 'DSA', 'DST', 'DSX']
[1389. 1170.  535.  581.  590.  310.   41.]
[22725. 16378.  7044. 16286.  9056.  5081.   626.]


In [259]:
print(tabCategoriesSignersUnitsFrames[:,:,0])
print(tabCategoriesSignersUnitsFrames[:,:,1])

[[7.18397086e-01 1.42805100e-01 1.07103825e-01 2.29508197e-02
  4.37158470e-03 4.37158470e-03]
 [6.93005181e-01 1.20466321e-01 1.37953368e-01 3.49740933e-02
  9.71502591e-03 3.88601036e-03]
 [7.55610973e-01 1.20947631e-01 9.80881131e-02 2.16126351e-02
  3.32502078e-03 4.15627598e-04]
 [8.52074236e-01 5.97707424e-02 7.53275109e-02 7.09606987e-03
  2.18340611e-03 3.54803493e-03]
 [8.06818182e-01 6.12947658e-02 1.00550964e-01 2.10055096e-02
  4.82093664e-03 5.50964187e-03]
 [6.75983437e-01 1.46997930e-01 1.33540373e-01 3.72670807e-02
  6.21118012e-03 0.00000000e+00]
 [7.97872340e-01 8.27423168e-02 7.03309693e-02 3.19148936e-02
  8.86524823e-03 8.27423168e-03]
 [7.62562814e-01 1.10552764e-01 9.79899497e-02 1.63316583e-02
  1.00502513e-02 2.51256281e-03]
 [7.05538462e-01 1.54153846e-01 1.15384615e-01 1.87692308e-02
  4.92307692e-03 1.23076923e-03]
 [7.85123967e-01 1.23966942e-01 5.78512397e-02 1.44628099e-02
  1.23966942e-02 6.19834711e-03]
 [6.71792948e-01 1.61665416e-01 1.45536384e-01 1.4

In [260]:
print(tabCategoriesTasksUnitsFrames[:,:,0])
print(tabCategoriesTasksUnitsFrames[:,:,1])

[[0.75595777 0.11161388 0.12156863 0.00965309 0.         0.00120664]
 [0.77812859 0.06458094 0.13318025 0.01492537 0.00086108 0.00832377]
 [0.80365438 0.05048002 0.12914215 0.01238774 0.00154847 0.00278724]
 [0.68426058 0.16310033 0.14194009 0.0085592  0.00095102 0.00118878]
 [0.73279196 0.13882444 0.0970611  0.02996906 0.         0.00135344]
 [0.75588921 0.11571318 0.10587626 0.02070929 0.         0.00181206]
 [0.76264304 0.12753784 0.07954965 0.02528608 0.00166113 0.00332226]
 [0.69568106 0.16810631 0.1076412  0.02458472 0.         0.00398671]
 [0.79695024 0.02126806 0.10674157 0.00802568 0.05377207 0.01324238]]
[[0.64083652 0.2337747  0.09875885 0.02390474 0.         0.0027252 ]
 [0.73090307 0.12029826 0.0867937  0.03791218 0.0008285  0.02326429]
 [0.7436584  0.10360051 0.11083771 0.03238647 0.00133888 0.00817804]
 [0.61764878 0.26121372 0.09422457 0.02371738 0.00093814 0.0022574 ]
 [0.57779112 0.25444962 0.0774158  0.08934261 0.         0.00100085]
 [0.69356449 0.19494115 0.0558833

In [261]:
np.array(idxUniqueSigners)

array(['A1', 'A10', 'A11', 'A2', 'A3', 'A6', 'A7', 'A9', 'B0', 'B13',
       'B14', 'B15', 'B16', 'B17', 'B4', 'B5'], dtype='<U3')