# Tuto

In [1]:
# Loading all helper functions
import sys
sys.path.insert(0, '..')
from src.models.data_utils import *
from src.models.model_utils import *
from src.models.train_model import *
from tqdm import tqdm

## General info:

### Code structure
- Helper functions are stored in src/models
- Data is stored in data/processed

### Corpora and annotation
#### Dicta-Sign
Annotations include (see more detail in the ortolang repo):
* **fls**: fully-lexical signs, encoded as categorical values (gloss indices)
* **PT**:    pointing signs, encoded as binary
* **PT_PRO1**, **PT_PRO2**, **PT_PRO3**, **PT_LOC**, **PT_DET**, **PT_LBUOY**, **PT_BUOY**: sub-categories for pointing signs, encoded as binary
* **DS**:    depicting signs, encoded as binary
* **DSA**, **DSG**, **DSL**, **DSM**, **DSS**, **DST**, **DSX**: sub-categories for depicting signs, encoded as binary
* **FBUOY**: fragment buoys, encoded as binary
* **N**:     numbering signs, encoded as binary
* **FS**:    fingerspelling signs, encoded as binary

#### NCSLGR
Annotations include (all data is binary):
* **lexical_with_ns_not_fs**: lexical signs, including numbering signs but excluding fingerspelling signs
* **fingerspelling**, **fingerspelled_loan_signs**: fingerspelling signs, finglerspelling loan signs
* **IX_1p**, **IX_2p**, **IX_3p**, **IX_loc**: sub-categories for pointing signs
* **POSS**, **SELF**: possessive pronouns
* **DCL**, **LCL**, **SCL**, **BCL**, **ICL**, **BPCL**, **PCL**: sub-categories for classifier signs (i.e. depicting signs)
* **gesture**: culturally shared gestures
* **part_indef**
* **other**

### Type of input features
Originally, this code was designed around preprocessed features for each frame. Possible features types are : 
- **2Draw**
- **2Draw_HS**
- **2Draw_HS_noOP**
- **2Draw_noHands**
- **2Dfeatures**
- **2Dfeatures_HS**
- **2Dfeatures_HS_noOP**
- **2Dfeatures_noHands**
- **3Draw**
- **3Draw_HS**
- **3Draw_HS_noOP**
- **3Draw_noHands**
- **3Dfeatures**
- **3Dfeatures_HS**
- **3Dfeatures_HS_noOP**
- **3Dfeatures_noHands**

which correspond to 2D or 3D data, raw OpenPose or preprocessed body and face data, including or excluding hand shape estimates, including or excluding OpenPose hand data.

The main data function `get_data_concatenated` requires a features dictionary, which can be obtained with the `getFeaturesDict` function.

Recently, we also added direct image input to the model, but it has not been tested thoroughly.

### Model outputs
The model can be trained for the recognition of:
- one or several (N) mixed linguistic descriptors in parallel, possibly simultaneously true. Each descriptor includes a 'garbage/other' class.
    - **ex. 1** (N = 4) : Y1 = [Y1_1 : lexical signs (categorical with 4 different signs), Y1_2 : pointing signs, Y1_3 : depicting signs, Y1_4 : fragment buoys]
    - **ex. 2** (N = 1) : Y2 = [Y2_1 : pointing signs to PRO1/2/3]
    - **ex. 3** (N = 2) : Y3 = [Y3_1 : pointing signs to PRO1/2/3, Y3_2 : depicting signs A/G]
    - **ex. 4** (N = 1) : Y4 = [Y4_1 : depicting signs]
- sign types, i.e. the most probable sign type for each frame. In this case, lexical signs are seen as binary.
    - **ex. 5**: Y5 = [other, lexical signs,  pointing signs, depicting signs, fragment buoys]. 
    - **ex. 6**: Y6 = [other, depicting signs] : this should give the same results as ex. 4

## Getting help on a function

In [2]:
# Use help(function_name)
# For instance:

help(categorical_conversion_seq)

Help on function categorical_conversion_seq in module src.models.data_utils:

categorical_conversion_seq(data, nonZeroCategories=[1])
    Converting annotations of one type to categorical values (for a sequence or a video).
    
    Inputs:
        data: a numpy array of annotations [time_steps, 1]
        nonZeroCategories: list of meaningful annotation categories
    
    Outputs:
        converted_data: categorical values of annotations [1, time_steps, categories]



## Main helper function for data handling (`data_utils.py`): `get_data_concatenated`

This is the main function, which enables to extract data in usable format for training.

`get_data_concatenated` returns [X_features, X_frames], Y, idx_trueData or [X_features, X_frames], Y (depending on return_idx_trueData)

#### Outputs
- **X_features** is a numpy array of size [1, total_time_steps, features_number] containing all retained preprocessed features for all retained frames
- **X_frames** is simply a list of paths for all retained frames (frames cannot be stored in memory directly, and will have to be read during training thanks to frames paths)
- **Y** is the annotation data (i.e. ground truth data) in the desired format

#### Inputs
- **corpus** (string)
- **output_form**:
    - 'mixed' if different and separated Outputs
    - 'sign_types' if annotation is only a binary matrix of sign types
- **output_names_final**: list of outputs (strings)
- **output_categories_or_names_original**:
    - if output_form: 'mixed': list of lists of meaningful annotation categories for each output
    - if output_form: 'sign_types': list of lists of original names that are used to compose final outputs
- **output_assemble**: used only if output_form: 'mixed'. List of lists of original names that can be assembled to compose final outputs, only considered if binary annotation category
- **features_dict**: a dictionary indication which features to keep ; e.g.: {'features_HS':np.arange(0, 420), 'features_HS_norm':np.array([]), 'raw':np.array([]), 'raw_norm':np.array([])}
- **preloaded_features**: if features are already loaded, in the format of a list (features for each video)
- **preloaded_annotations**: if annotations are already loaded, in the format of a list of lists (for each output type, each video), categorical values
- **video_indices**: numpy array for a list of videos
- **separation**: in order to separate consecutive videos
- **from_notebook**: if notebook script, data is in parent folder
- **return_idx_trueData**: if True, returns a binary vector with 0 where separations are
- **features_type**: 'features', 'frames', 'both'

## Main helper function for model handling (`model_utils.py`): `get_model`

This is the main function, which enables to obtain the Keras model.

`get_model` returns a Keras model

#### Outputs
- a Keras model

#### Inputs
- **output_names**: list of outputs (strings)
- **output_classes**: list of number of classes of each output type
- **output_weights**: list of weights for each_output
- **conv** (bool): if True, applies convolution on input
- **conv_filt**: number of convolution filters
- **conv_ker**: size of convolution kernel
- **conv_strides**: size of convolution strides
- **rnn_number**: number of recurrent layers
- **rnn_type**: type of recurrent layers (string)
- **rnn_hidden_units**: number of hidden units
- **dropout**: how much dropout (0 to 1)
- **att_in_rnn**: if True, applies attention layer before recurrent layers
- **att_in_rnn_single**: single (shared) attention layer or not
- **att_in_rnn_type** (string): timewise or featurewise attention layer
- **att_out_rnn**: if True, applies attention layer after recurrent layers
- **att_out_rnn_single**: single (shared) attention layer or not
- **att_out_rnn_type** (string): timewise or featurewise attention layer
- **rnn_return_sequences**: if False, only last timestep of recurrent layers is returned
- **classif_local** (bool): whether classification is for each timestep (local) of globally for the sequence
- **mlp_layers_number**: number of additional dense layers
- **mlp_layers_size**: size of additional dense layers
- **optimizer**: gradient optimizer type (string)
- **learning_rate**: learning rate (float)
- **time_steps**: length of sequences (int)
- **features_number**: number of features (int)
- **features_type**: 'features' (1D vector of features), 'frames' (for a CNN processing) or 'both'
- **img_height** and **img_width**: size of CNN input
- **cnnType**: 'resnet', 'vgg' or 'mobilenet'
- **cnnFirstTrainedLayer**: index of first trainable layer in CNN (int)
- **cnnReduceDim**: if greater than 0, size of CNN flattened output is reduced to cnnReduceDim
- **print_summary** (bool)

## Building data and model together 

In these examples we analyze the different types of output form Y

In [3]:
# let us split train/valid/test videos
# In this case we split by signers in a manual fashion

idxTrain, idxValid, idxTest = getVideoIndicesSplitDictaSign(tasksTrain=[],
                                                            tasksValid=[],
                                                            tasksTest=[],
                                                            signersTrain=[0,1,2,3,4,5,6,7,8,9],
                                                            signersValid=[10,11,12],
                                                            signersTest=[13,14,15],
                                                            excludeTask9=False,
                                                            videoSplitMode='manual',
                                                            checkSplits=True,
                                                            checkSets=True,
                                                            from_notebook=True)

Number of videos:
Train: 66
Valid: 10
Test: 18
Total: 94


In [39]:
# Getting a dictionary for desired preprocessed features
# In this case we ask for normalized 3Dfeatures_HS (this correspond to a total number of 420 features):

features_dict, features_number = getFeaturesDict(inputType='3Dfeatures_HS', inputNormed=True)

print(features_dict)
print(features_number)

{'features_HS': array([], dtype=float64), 'features_HS_norm': array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
  

### First category of examples: `output_form = 'mixed'` (examples 1 to 4)

#### ex. 1 :

##### Data

In [5]:
import csv

idGloss = {}

with open('Dicta-Sign-LSF_ID.csv', newline='') as csvfile:
    glossreader = csv.reader(csvfile, delimiter=';', quotechar='|')
    for row in glossreader:
        idGloss[row[0]] = row[1]

In [6]:
# we only consider 4 lexical signs, indices 41891,43413,43422,42992

flsKept = [41891,43413,43422,42992]

# that correspond to glosses:

for i in flsKept:
    print(idGloss[str(i)])

PARIS3 (TOUR EIFFEL):NS
RESTAURANT
QUALITE-DE GRANDE /EXCELLENT
VISITER1:VAR


In [7]:
[X_feat_train_1, X_frames_train_1], Y_train_1 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            output_names_final=['fls', 'DS', 'PT', 'FBUOY'],
                            output_categories_or_names_original=[flsKept, [1], [1], [1]],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [8]:
print(X_feat_train_1.shape)
print(X_frames_train_1.shape)
print(len(Y_train_1))

(1, 665612, 420)
(665612,)
4


As can be seen above, X_feat is a big matrix storing all 420 preprocessed features for each frame. We can print the first 15 features for frame number 192:

In [9]:
print(X_feat_train_1[0,192,0:15])

[2.35301688e-01 1.29614295e-02 2.68831011e-02 3.30785895e-03
 1.42225486e-04 1.38188677e-03 2.03026459e-02 2.27585621e-03
 1.62972094e-04 2.75143277e-04 1.34467043e-03 6.37093792e-03
 6.20781793e-05 3.47524241e-04 8.72815102e-02]


X_frames stores paths for all frames:

In [10]:
X_frames_train_1[192]

'/localHD/DictaSign/convert/img/DictaSign_lsf_S5_T1_A9_front/00193.jpg'

Y_train stores the 4 linguistic descriptors annotation:

In [11]:
print(Y_train_1[0].shape)
print(Y_train_1[1].shape)
print(Y_train_1[2].shape)
print(Y_train_1[3].shape)

(1, 665612, 5)
(1, 665612, 2)
(1, 665612, 2)
(1, 665612, 2)


In [12]:
print(Y_train_1[0][0,192,:])
print(Y_train_1[1][0,192,:])
print(Y_train_1[2][0,192,:])
print(Y_train_1[3][0,192,:])

[1. 0. 0. 0. 0.]
[1. 0.]
[1. 0.]
[1. 0.]


Frame 192 is annotated as non-lexical, depicting, non-pointing, non-fbuoy

##### Model

In [13]:
# training model can be built to take preprocessed features as input, frames as input or both
model_1_features = get_model(output_names=['fls', 'DS', 'PT', 'FBUOY'],
                    output_classes=[5,2,2,2],
                    output_weights=[1,1,1,1],
                    features_number=features_number,
                    features_type='features')

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, 100, 200)     252200      input_1[0][0]                    
__________________________________________________________________________________________________
bidirectional (Bidirectional)   (None, 100, 110)     112640      conv1d[0][0]                     
__________________________________________________________________________________________________
bidirectional_1 (Bidirectional) (None, 100, 110)     73040       bidirectional[0][0]              
______________________________________________________________________________________________

In [14]:
model_1_frames = get_model(output_names=['fls', 'DS', 'PT', 'FBUOY'],
                    output_classes=[5,2,2,2],
                    output_weights=[1,1,1,1],
                    features_number=features_number,
                    features_type='frames')

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 100, 224, 22 0                                            
__________________________________________________________________________________________________
time_distributed_4 (TimeDistrib (None, 100, 2048)    23587712    input_2[0][0]                    
__________________________________________________________________________________________________
bidirectional_2 (Bidirectional) (None, 100, 110)     925760      time_distributed_4[0][0]         
__________________________________________________________________________________________________
bidirectional_3 (Bidirectional) (None, 100, 110)     73040       bidirectional_2[0][0]            
____________________________________________________________________________________________

In [15]:
model_1_both = get_model(output_names=['fls', 'DS', 'PT', 'FBUOY'],
                    output_classes=[5,2,2,2],
                    output_weights=[1,1,1,1],
                    features_number=features_number,
                    features_type='both')

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
input_5 (InputLayer)            [(None, 100, 224, 22 0                                            
__________________________________________________________________________________________________
conv1d_1 (Conv1D)               (None, 100, 200)     252200      input_4[0][0]                    
__________________________________________________________________________________________________
time_distributed_9 (TimeDistrib (None, 100, 2048)    23587712    input_5[0][0]                    
____________________________________________________________________________________________

#### ex. 2 :

##### Data

In [16]:
# in this example, data from 3 channels (PT_PRO1, 2 and 3) are assembled to form a new category
[X_feat_train_2, X_frames_train_2], Y_train_2 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            output_names_final=['pointing-signs-pro123'],
                            output_categories_or_names_original=[[1]],
                            output_assemble=[['PT_PRO1','PT_PRO2', 'PT_PRO3']],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [18]:
print(X_feat_train_2.shape)
print(X_frames_train_2.shape)
print(len(Y_train_2))

(1, 665612, 420)
(665612,)
1


In [19]:
print(Y_train_2[0].shape)

(1, 665612, 2)


##### Model

In [32]:
# using only preprocessed features as input:
model_2_features = get_model(output_names=['pointing-signs-pro123'],
                    output_classes=[2],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_6 (Bidirection (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_7 (Bidirection (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_14 (TimeDis (None, 100, 2)            222       
Total params: 438,102
Trainable params: 438,102
Non-trainable params: 0
_________________________________________________________________


#### ex. 3 :

##### Data

In [33]:
# in this example, data from 3 channels (PT_PRO1, 2 and 3) are assembled to form a new category
# and data from 2 channels (DSA, DSG) are assembled to form a second category
[X_feat_train_3, X_frames_train_3], Y_train_3 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            output_names_final=['pointing-signs-pro123', 'depicting-signs-AG'],
                            output_categories_or_names_original=[[1],[1]],
                            output_assemble=[['PT_PRO1','PT_PRO2', 'PT_PRO3'], ['DSA', 'DSG']],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [34]:
print(X_feat_train_3.shape)
print(X_frames_train_3.shape)
print(len(Y_train_3))

(1, 665612, 420)
(665612,)
2


In [35]:
print(Y_train_3[0].shape)
print(Y_train_3[1].shape)

(1, 665612, 2)
(1, 665612, 2)


##### Model

In [36]:
# using only preprocessed features as input:
model_3_features = get_model(output_names=['pointing-signs-pro123', 'depicting-signs-AG'],
                    output_classes=[2, 2],
                    output_weights=[1, 1],
                    features_number=features_number,
                    features_type='features')

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_8 (InputLayer)            [(None, 100, 420)]   0                                            
__________________________________________________________________________________________________
conv1d_3 (Conv1D)               (None, 100, 200)     252200      input_8[0][0]                    
__________________________________________________________________________________________________
bidirectional_8 (Bidirectional) (None, 100, 110)     112640      conv1d_3[0][0]                   
__________________________________________________________________________________________________
bidirectional_9 (Bidirectional) (None, 100, 110)     73040       bidirectional_8[0][0]            
____________________________________________________________________________________________

#### ex. 4 :

##### Data

In [40]:
# in this example, only depicting signs as output
[X_feat_train_4, X_frames_train_4], Y_train_4 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='mixed',
                            output_names_final=['DS'],
                            output_categories_or_names_original=[[1]],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [41]:
print(X_feat_train_4.shape)
print(X_frames_train_4.shape)
print(len(Y_train_4))

(1, 665612, 420)
(665612,)
1


In [42]:
print(Y_train_4[0].shape)

(1, 665612, 2)


##### Model

In [59]:
# using only preprocessed features as input:
model_4_features = get_model(output_names=['DS'],
                    output_classes=[2],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_10 (Bidirectio (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_11 (Bidirectio (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_17 (TimeDis (None, 100, 2)            222       
Total params: 438,102
Trainable params: 438,102
Non-trainable params: 0
_________________________________________________________________


### Second category of examples: `output_form = 'sign_types'` (examples 5 and 6)

#### ex. 5 :

##### Data

In [45]:
[X_feat_train_5, X_frames_train_5], Y_train_5 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='sign_types',
                            output_names_final=['lexical', 'depicting', 'pointing', 'frag.buoy'],
                            output_categories_or_names_original=[['fls'],['DS'],['PT'],['FBUOY']],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [51]:
print(X_feat_train_5.shape)
print(X_frames_train_5.shape)
print(Y_train_5.shape) # when output_form='sign_types', Y is not a list, but a matrix

(1, 665612, 420)
(665612,)
(1, 665612, 5)


In [56]:
print(Y_train_5[0,1000:1020,:])

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


##### Model

In [60]:
# using only preprocessed features as input:
model_5_features = get_model(output_names=['fls-DS-PT-FBUOY'],
                    output_classes=[5],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_12 (Bidirectio (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_13 (Bidirectio (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_18 (TimeDis (None, 100, 5)            555       
Total params: 438,435
Trainable params: 438,435
Non-trainable params: 0
_________________________________________________________________


#### ex. 6 :

##### Data

In [63]:
[X_feat_train_6, X_frames_train_6], Y_train_6 =\
      get_data_concatenated(corpus='DictaSign',
                            output_form='sign_types',
                            output_names_final=['depicting'],
                            output_categories_or_names_original=[['DS']],
                            video_indices=idxTrain,
                            features_dict=features_dict,
                            features_type='both',
                            from_notebook=True)

In [65]:
print(X_feat_train_6.shape)
print(X_frames_train_6.shape)
print(Y_train_6.shape) # when output_form='sign_types', Y is not a list, but a matrix

(1, 665612, 420)
(665612,)
(1, 665612, 2)


In [66]:
print(Y_train_6[0,1000:1020,:])

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


##### Model

In [68]:
# using only preprocessed features as input:
model_6_features = get_model(output_names=['DS'],
                    output_classes=[2],
                    output_weights=[1],
                    features_number=features_number,
                    features_type='features')

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 100, 420)]        0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 100, 200)          252200    
_________________________________________________________________
bidirectional_14 (Bidirectio (None, 100, 110)          112640    
_________________________________________________________________
bidirectional_15 (Bidirectio (None, 100, 110)          73040     
_________________________________________________________________
time_distributed_19 (TimeDis (None, 100, 2)            222       
Total params: 438,102
Trainable params: 438,102
Non-trainable params: 0
_________________________________________________________________


In [71]:
data = np.array([0,2,3,1,0,2])
list_true = [2,3]

In [70]:
data>0

array([False,  True,  True,  True, False,  True])

In [86]:
np.in1d(data.flatten(), list_true)

array([False,  True,  True, False, False,  True])

In [1]:
import sys
sys.path.insert(0, '..')
from src.models.data_utils2 import *

In [2]:
a=get_concatenated_sign_types('DictaSign', [['PT'], ['fls', 'PT']], [[], []], video_indices=np.arange(10), provided_annotation=None, from_notebook=True)
b=get_concatenated_mixed('DictaSign', [['PT'], ['fls']], [[], [41891,43413,42495,42093]], [True,True], video_indices=np.arange(10), provided_annotation=None, from_notebook=True)

In [3]:
get_sequence('DictaSign',
                 'sign_types',
                 [['DSA', 'DSG', 'DSS', 'DST'], ['fls']],
                 [[],[]],
                 binary=[False,False],
                 video_index=10,
                 img_start_idx=54,from_notebook=True)

([array([[[ 1.66951660e-02,  2.06301731e-04,  1.37241059e-05, ...,
           -2.56454825e-05, -4.75219441e-05,  1.40270823e-04],
          [ 1.81659274e-02,  1.29892695e-04,  1.97745358e-05, ...,
            9.23101807e-05,  1.12431948e-04, -3.33634985e-04],
          [ 1.96804684e-02,  1.24690021e-04,  2.11701008e-05, ...,
            3.01147330e-05, -6.29835372e-05,  2.02058748e-04],
          ...,
          [ 6.27725303e-01,  6.87061772e-02,  8.08450207e-02, ...,
            3.59313385e-04, -1.19492622e-04,  3.97208547e-04],
          [ 5.50382555e-01,  2.70885557e-01,  7.86253344e-03, ...,
            9.03627155e-05,  7.09919911e-05, -2.29932257e-04],
          [ 6.10148191e-01,  1.33991688e-02,  2.40684976e-03, ...,
            2.80272445e-04, -1.52892200e-04,  5.04497824e-04]]]),
  array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
         '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
         '', '', '', '', '', '', '', '', '', '',

In [9]:
get_sequence('DictaSign',
                 'mixed',
                 [['fls'], ['DS'], ['PT'], ['FBUOY']],
                 [[41891,43413,43422,42992],[],[],[]],
                 binary=[False,True,True,True],
                 video_index=0,
                 img_start_idx=4,from_notebook=True,time_steps=300)

([array([[[ 9.19201016e-01,  3.51054368e-05,  1.28861739e-05, ...,
           -5.60852137e-04,  5.03595539e-05, -6.92644472e-04],
          [ 9.39777792e-01,  1.51432496e-05,  1.14073109e-05, ...,
           -6.44192655e-04,  1.76235969e-04, -7.74923055e-04],
          [ 9.89504933e-01,  2.20477045e-06,  1.61030403e-06, ...,
           -4.31502034e-04,  1.87778910e-04, -6.51685846e-04],
          ...,
          [ 5.35631292e-02,  2.62070168e-03,  3.60934949e-03, ...,
           -7.38186812e-05,  2.91011405e-05, -1.19557619e-04],
          [ 5.70065491e-02,  1.52368390e-04,  1.50080118e-03, ...,
           -7.27640494e-05, -4.13706014e-05,  7.30804536e-05],
          [ 9.00104120e-02,  2.46888172e-04,  1.81303429e-03, ...,
           -1.10089788e-04, -1.97133194e-05, -4.15525019e-06]]]),
  array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
         '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
         '', '', '', '', '', '', '', '', '', '',

In [12]:
[X_features, X_frames], Y = get_data_concatenated('DictaSign',
                 'mixed',
                 [['fls'], ['DS'], ['PT'], ['FBUOY']],
                 [[41891,43413,43422,42992],[],[],[]],
                 binary=[False,True,True,True],
                          video_indices=np.arange(5),from_notebook=True)

In [14]:
np.sum(Y[0],axis=1)

array([[5.2107e+04, 0.0000e+00, 1.4000e+01, 0.0000e+00, 1.6000e+01]],
      dtype=float32)